dashboard/dashboard/blueprints/auth.py
from flask import Blueprint, redirect, url_for, render_template, flash, g
from flask_login import current_user, login_user, logout_user, login_required

from ..forms import RegisterForm, LoginForm
from ..models import User
from ..extension import login_manager, db

auth_bp = Blueprint("auth", __name__, url_prefix="/auth")


@login_manager.user_loader
def load_user(user_id):
    user = User.query.get(int(user_id))
    return user


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index"))

    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        user = User(username=username, email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash("Registered successfully! Please login to continue.")
        return redirect(url_for("auth.login"))

    return render_template("auth/register.html", form=form)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("index"))

    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        remember = form.remember.data
        user = g.user
        login_user(user, remember)
        flash("Welcome back, %s!" % user.username)
        return redirect(url_for("index"))

    return render_template("auth/login.html", form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have logged out.")
    return redirect(url_for(".login"))

dashboard/dashboard/blueprints/task.py
import time
import uuid
import shutil
import psutil
from pathlib import Path
from flask import (
    request,
    abort,
    Blueprint,
    render_template,
    flash,
    redirect,
    url_for,
    current_app,
    send_file,
)
from flask_login import login_required, current_user

from ..forms import TaskForm
from ..models import Task
from ..extension import db
from ..tasks import run_locust, run_spark

task_bp = Blueprint("task", __name__, url_prefix="/task")


@task_bp.route("/submit", methods=["GET", "POST"])
@login_required
def submit():
    form = TaskForm()
    if form.validate_on_submit():
        type = form.type.data
        name = form.name.data
        zipfile = form.zipfile.data
        id = uuid.uuid4().hex
        upload_dir = current_app.config[type + "_UPLOAD_DIR"]
        zipfile.save(Path(upload_dir, id + ".zip"))
        task = start_task(type, name, id)
        task.user = current_user._get_current_object()
        db.session.add(task)
        db.session.commit()
        flash(f'Task "{task.name}" has been submitted successfully!')
        return redirect(url_for("index"))
    return render_template("submit.html", form=form)


def start_task(type, name, id):
    if type == "LOCUST":
        result = run_locust.apply_async(args=(id,), task_id=id)
    elif type == "SPARK":
        result = run_spark.apply_async(args=(id,), task_id=id)
    else:
        abort(500)
    while result.info is None:
        time.sleep(current_app.config["POLL_INTERVAL"])
    info = result.info
    status = "PENDING"
    pid = info["pid"]
    progress = int(info["success"] / info["total"] * 100.0)
    task = Task(
        id=id, name=name, type=type, status=status, pid=pid, progress=progress
    )
    return task


def update_tasks(tasks):
    for task in tasks:
        if task.status == "SUCCESS" or task.status == "FAILURE":
            continue
        type = task.type
        id = task.id
        if type == "LOCUST":
            task_obj = run_locust
        elif type == "SPARK":
            task_obj = run_spark
        result = task_obj.AsyncResult(id)
        info = result.info
        task.status = info["status"]
        task.progress = int(info["success"] / info["total"] * 100.0)
        if task.status == "SUCCESS" or task.status == "FAILURE":
            task.pid = None
            result.forget()
        db.session.add(task)
    db.session.commit()


@task_bp.route("/<task_id>/download", methods=["GET"])
@login_required
def download(task_id):
    task = Task.query.get_or_404(task_id)
    if task.user.id != current_user.id:
        abort(404)
    if task.status != "SUCCESS" and task.status != "FAILURE":
        abort(404)
    download_dir = current_app.config[task.type + "_DOWNLOAD_DIR"]
    path = Path(download_dir, task_id + ".zip")
    if not path.exists():
        abort(404)
    return send_file(
        path, as_attachment=True, attachment_filename=task.name + ".zip"
    )


@task_bp.route("/<task_id>/delete", methods=["POST"])
@login_required
def delete(task_id):
    task = Task.query.get_or_404(task_id)
    if task.user.id != current_user.id:
        abort(404)
    if request.form["taskname"] != task.name:
        flash(f"Wrong task name detected!")
        return redirect(url_for("index"))
    if task.status != "SUCCESS" and task.status != "FAILURE":
        abort(404)
    upload_dir = current_app.config[task.type + "_UPLOAD_DIR"]
    run_dir = current_app.config[task.type + "_RUN_DIR"]
    download_dir = current_app.config[task.type + "_DOWNLOAD_DIR"]
    upload_path = Path(upload_dir, task_id + ".zip")
    run_path = Path(run_dir, task_id)
    download_path = Path(download_dir, task_id + ".zip")
    upload_path.unlink()
    download_path.unlink()
    if run_path.exists():
        shutil.rmtree(run_path, ignore_errors=True)
    db.session.delete(task)
    db.session.commit()
    flash(f'Task "{task.name}" deleted!')
    return redirect(url_for("index"))


@task_bp.route("/<task_id>/cancel", methods=["POST"])
@login_required
def cancel(task_id):
    task = Task.query.get_or_404(task_id)
    if task.user.id != current_user.id:
        abort(404)
    if request.form["taskname"] != task.name:
        flash(f"Wrong task name detected!")
        return redirect(url_for("index"))
    update_tasks([task])
    if task.status == "SUCCESS" or task.status == "FAILURE":
        abort(404)
    if task.type == "LOCUST":
        task_obj = run_locust
    elif task.type == "SPARK":
        task_obj = run_spark
    task_result = task_obj.AsyncResult(task.id)
    proc = psutil.Process(task.pid)
    children = proc.children(recursive=True)
    task_result.revoke(terminate=True)
    for child in children:
        child.terminate()
    task.status = "FAILURE"
    task.pid = None
    db.session.add(task)
    db.session.commit()
    flash(f'Task "{task.name}" has been cancelled!')
    return redirect(url_for("index"))

dashboard/dashboard/templates/_footer.html
<footer class="bg-white sticky-footer">
    <div class="container my-auto">
        <div class="text-center my-auto copyright"><span>Copyright © neothenil 2020</span></div>
    </div>
</footer>

dashboard/dashboard/templates/_sidebar.html
<nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
    <div class="container-fluid d-flex flex-column p-0">
        <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{{ url_for('index') }}">
            <div class="sidebar-brand-icon"><i class="far fa-chart-bar"></i></div>
            <div class="sidebar-brand-text mx-1"><span>Task Dashboard</span></div>
        </a>
        <hr class="sidebar-divider my-0">
        <ul class="nav navbar-nav text-light" id="accordionSidebar">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" href="{{ url_for('index') }}">
                    <i class="fas fa-tachometer-alt"></i>
                    <span>Status</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link active" href="{{ url_for('task.submit') }}">
                    <i class="fas fa-upload"></i>
                    <span>Submit</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link active" href="{{ url_for('auth.logout') }}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link active" href="{{ url_for('help') }}">
                    <i class="fas fa-question-circle"></i>
                    <span>Help</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

dashboard/dashboard/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nunito.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome-all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body id="page-top">
    <div id="wrapper">
        {% include '_sidebar.html' %}
        <div class="d-flex flex-column" id="content-wrapper">
            {% block content %}
            {% endblock content %}
            {% include '_footer.html' %}
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.easing.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.min.js') }}"></script>
</body>

</html>

dashboard/dashboard/templates/help.html
{% extends 'base.html' %}
{% from 'macros.html' import page_name, message_card %}

{% block title %}Dashboard - Help{% endblock title %}

{% block content %}
<div id="content">
    <div class="container-fluid">
        {{ page_name('Help') }}
        {% for msg in get_flashed_messages() %}
        {{ message_card(msg) }}
        {% endfor %}
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="text-primary m-0 font-weight-bold">Q: What is the structure of zip file for LOCUST task?</h6>
            </div>
            <div class="card-body">
                <p class="m-0">A: The contents of LOCUST zip file are a collection of directories, 
                with each containing an xml file as the input file for LOCUST. It's usually a good practice to make the 
                directory and the xml file in it have a same basename. For example, the xml file in directory 180000 has name
                180000.xml. Here are some LOCUST zip files for demostration: 
                <ul>
                {% for zipfile in locust_zipfiles %}
                    <li><a href="{{ url_for('demo', type='locust', filename=zipfile + '.zip') }}">{{ zipfile }}</a></li>
                {% endfor %}
                </ul>
                </p>
            </div>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="text-primary m-0 font-weight-bold">Q: What is the structure of zip file for SPARK task?</h6>
            </div>
            <div class="card-body">
                <p class="m-0">A: The contents of SPARK zip file are also a collection of directories.
                You can put any relative files and directories to it, such as LTOS directory.
                But what really matters is the directories containing a spark.inp file. Typically, 
                each of these directories represents a cycle for a reactor core. And SPARK will be executed in
                these directories in alphabetical order. Here are some SPARK zip files for demostration:
                <ul>
                {% for zipfile in spark_zipfiles %}
                    <li><a href="{{ url_for('demo', type='spark', filename=zipfile + '.zip') }}">{{ zipfile }}</a></li>
                {% endfor %}
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

dashboard/dashboard/templates/index.html
{% extends 'base.html' %}
{% from 'macros.html' import page_name, message_card, show_task %}

{% block title %}Dashboard - Status{% endblock title %}

{% block content %}
<div id="content">
    <div class="container-fluid">
        {{ page_name('Status') }}
        {% for msg in get_flashed_messages() %}
        {{ message_card(msg) }}
        {% endfor %}
        <div class="row">
            <div class="col-lg-6 mb-4">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="text-primary font-weight-bold m-0">LOCUST</h6>
                    </div>
                    <div class="card-body">
                        {% if locust_tasks %}
                        {% for task in locust_tasks %}
                            {{ show_task(task) }}
                        {% endfor %}
                        {% else %}
                        <h4 class="small font-weight-bold">Empty task. <a href="{{ url_for('task.submit') }}">Submit Now!</a></h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="text-primary font-weight-bold m-0">SPARK</h6>
                    </div>
                    <div class="card-body">
                        {% if spark_tasks %}
                        {% for task in spark_tasks %}
                            {{ show_task(task) }}
                        {% endfor %}
                        {% else %}
                        <h4 class="small font-weight-bold">Empty task. <a href="{{ url_for('task.submit') }}">Submit Now!</a></h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

dashboard/dashboard/templates/macros.html
{% macro page_name(name) %}
<div class="d-sm-flex justify-content-between align-items-center mb-4">
    <h3 class="text-dark mb-0">{{ name }}</h3>
</div>
{% endmacro %}

{% macro message_card(msg) %}
<div class="card shadow border-left-info py-2 message">
    <div class="card-body message-body">
        <div class="row align-items-center no-gutters">
            <div class="col mr-2">
                <div class="text-dark h6 mb-0"><span>{{ msg }}</span></div>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

{% macro show_task(task) %}
<h4 class="small font-weight-bold">{{ task.name }}<span class="float-right">
{% if task.status != 'FAILURE' %}
{{ task.progress }}%
{% else %}
Failed
{% endif %}&nbsp;
{% if task.status == 'PENDING' or task.status == 'STARTED' %}
<a href="#" data-toggle="modal" data-target="#cancel-task-{{ task.id }}">Cancel</a>
{% else %}
<a href="{{ url_for('task.download', task_id=task.id) }}">Download</a>&nbsp;<a href="#" data-toggle="modal" data-target="#delete-task-{{ task.id }}">Delete</a>
{% endif %}</span></h4>
{% if task.progress <= 20 %}
{% set color = 'danger' %}
{% elif task.progress <= 40 %}
{% set color = 'warning' %}
{% elif task.progress <= 60 %}
{% set color = 'primary' %}
{% elif task.progress <= 80 %}
{% set color = 'info' %}
{% else %}
{% set color = 'success' %}
{% endif %}
<div class="progress mb-4">
    <div class="progress-bar bg-{{ color }}" aria-valuenow="{{ task.progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ task.progress }}%;"></div>
</div>
{% if task.status == 'PENDING' or task.status == 'STARTED' %}
<form action="{{ url_for('task.cancel', task_id=task.id) }}" method="POST">
    <div class="modal fade" role="dialog" tabindex="-1" id="cancel-task-{{ task.id }}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Cancel Task</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button></div>
                <div class="modal-body">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <p>Please input the task name `{{ task.name }}` to confirm you really want to cancel this task.</p>
                    <input type="text" name="taskname" placeholder="Task Name" style="width: 50%;">
                </div>
                <div class="modal-footer">
                <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
                </div>
            </div>
        </div>
    </div>
</form>
{% else %}
<form action="{{ url_for('task.delete', task_id=task.id) }}" method="POST">
    <div class="modal fade" role="dialog" tabindex="-1" id="delete-task-{{ task.id }}">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Task</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button></div>
                <div class="modal-body">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <p>Please input the task name `{{ task.name }}` to confirm you really want to delete this task.</p>
                    <input type="text" name="taskname" placeholder="Task Name" style="width: 50%;">
                </div>
                <div class="modal-footer">
                <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
                </div>
            </div>
        </div>
    </div>
</form>
{% endif %}
{% endmacro %}

{% macro form_field(field) %}
<div class="form-group">
    {{ field(**kwargs) }}
    {% if field.errors %}
    {% for error in field.errors %}
        <small class="danger">{{ error }}</small>
    {% endfor %}
    {% endif %}
</div>
{% endmacro %}

{% macro form_checkbox(field) %}
<div class="form-group">
    <div class="custom-control custom-checkbox small">
        <div class="form-check">
            {{ field(class_='form-check-input custom-control-input') }}
            {{ field.label(class_='form-check-label custom-control-label') }}
        </div>
    </div>
</div>
{% endmacro %}

dashboard/dashboard/templates/submit.html
{% extends 'base.html' %}
{% from 'macros.html' import page_name, message_card, form_field %}

{% block title %}Dashboard - Submit Task{% endblock title %}

{% block content %}
<div id="content">
    <div class="container-fluid">
        {{ page_name('Submit Task') }}
        {% for msg in get_flashed_messages() %}
        {{ message_card(msg) }}
        {% endfor %}
        <div class="row">
            <div class="col-lg-6 mb-4">
                <form action="{{ url_for('task.submit') }}" method="POST" enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    {{ form.type.label }}
                    {{ form_field(form.type, class_='form-control form-control-user', placeholder='Select task type...') }}
                    {{ form.name.label }}
                    {{ form_field(form.name, class_='form-control form-control-user', placeholder='Task Name')}}
                    {{ form.zipfile.label }}
                    {{ form_field(form.zipfile, class_='form-control form-control-user',
                    placeholder='Upload the essential file (zip format)') }}
                    <p><a href="{{ url_for('help') }}">Need help?</a></p>
                    {{ form.submit(class_='btn btn-primary btn-block text-white btn-user') }}
                    <hr>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}